Remove redundant imports and code. (Linting)
lancelet/bored-robot pull request #49
Opened 2017-04-13 02:51 UTC by pmellati

Brought to you by my atom IDE.

2017-04-13 04:02 UTC, jberthold requested changes
Generally unsure about doing this just yet (although it is great Puria got a nice setup to put it together.
And, please do not change the main application, it is far from ready.

2017-04-13 04:02 UTC, jberthold commented on app/DockerFu.hs
> -dockerTodo :: (Member Trace r)
This (part of this) file will change substantially in a forthcoming pull request.
Can we take it (and `docker-fu.hs`) out of the PR please?

In general I am a bit in doubt about clean-up only" patches

2017-04-13 04:02 UTC, jberthold commented on app/docker-fu.hs
> -import Options.Applicative
Same comment here: please do not edit this file yet.

2017-04-17 07:59 UTC, pmellati commented
@jberthold I've taken the two "docker fu" files out of the PR.

2017-04-17 23:48 UTC, jberthold commented
OK, thanks for revisiting. LGTM now

2017-04-17 23:49 UTC, jberthold approved these changes

2017-04-17 23:58 UTC, merged